### ISSUE TITLE
rpx 是什么尺寸单位

### ISSUE THREAD

**Issue by yuancaoscott** [if-information/wxapp#2]
涉及到手机等移动端开发时, 经常提到 `rpx` 尺寸单位, 但不是很明确 `rpx` 尺寸单位.

**Comment by Mark-Ming** [comment]
# C01_尺寸单位rpx的介绍
### 官方文档做了简要介绍：[点击前往](https://mp.weixin.qq.com/debug/wxadoc/dev/framework/view/wxss.html)
#### rpx（responsive pixel）: 可以根据屏幕宽度进行自适应。规定屏幕宽为750rpx。
#### 如在 iPhone6 上，屏幕宽度为375px，共有750个物理像素，则750rpx = 375px = 750物理像素，1rpx = 0.5px = 1物理像素。
![2018-01-19 2 55 42](https://user-images.githubusercontent.com/8563636/35138304-e240ca08-fd28-11e7-99db-b79f5ce8c3f2.png)

### 官方的建议：
**建议： 开发微信小程序时设计师可以用 iPhone6 作为视觉稿的标准。**
**注意： 在较小的屏幕上不可避免的会有一些毛刺，请在开发时尽量避免这种情况。**

**Comment by Mark-Ming** [comment]
# C02_一篇关于rpx的博客
## [点击前往](https://segmentfault.com/a/1190000007220703)
